### ISSUE TITLE
Some Errors 

### ISSUE THREAD

**Issue by kaiyaf57** [kamronbek29/tiktok_views#1]
@kamronbek29 

Python 3.8 and all dependencies are installed and working. 

tiktok.py opens in CMD and I can enter the video link. 
I press ENTER and the CMD window closes immediately without any visible interaction.

**Comment by kamronbek29** [comment]
@kaiyaf57 Hello, i wrote this script with python3.7, may be this is the problem. Anyway i will try to fix it

**Comment by mikejack99** [comment]
@kamronbek29 

All dependencies are installed and working too.

when i put the video link and press enter, appear this message:

"Traceback (most recent call last):
  File "tiktok.py", line 75, in <module>
    asyncio.run(get_video_url(video_url))
  File "C:\Users\diego\AppData\Local\Programs\Python\Python38-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\diego\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "tiktok.py", line 61, in get_video_url
    video_id = await get_video_id(link)
  File "tiktok.py", line 15, in get_video_id
    video_id = str(correct_url).split('com/v/')[1].split('.html?')[0]
IndexError: list index out of range
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x030EDEC8>
Traceback (most recent call last):
  File "C:\Users\diego\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\diego\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\diego\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\diego\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed"

**Comment by kamronbek29** [comment]
Hi @mikejack99 , I have updated the script just now, it should work now. Try it
